name: Linux q2admin (64-bit)

on:
  push:
    branches: ["master", "aqtion"]

jobs:
  linux_x86_64_build_q2admin:
    runs-on: [self-hosted, x86]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: actionquake/q2admin
          path: build

      - name: Rename config.ex.lua
        working-directory: build/src
        run: |
          mv ../config.ex.lua ../config.lua

      - name: Build q2admin
        working-directory: build
        run: make -j2 V=1
        env:
          CC: "gcc"

      - name: Generate archive
        uses: actions/upload-artifact@v3
        with:
          name: q2admin-lin-x86_64-library
          path: |
            build/gamex86_64.so
            build/plugins
            build/config.lua
            build/versions

  linux_arm64_build_q2admin:
    runs-on: [self-hosted, ARM64]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: actionquake/q2admin
          path: build

      - name: Rename config.ex.lua
        working-directory: build/src
        run: |
          mv ../config.ex.lua ../config.lua

      - name: Build q2admin
        working-directory: build
        run: make -j2 V=1
        env:
          CC: "gcc"

      - name: Generate archive
        uses: actions/upload-artifact@v3
        with:
          name: q2admin-lin-arm64-library
          path: |
            build/gameaarch64.so
            build/plugins
            build/config.lua
            build/versions